### ISSUE TITLE
Feature request: Folders should have an anchor tag instead of a div.

### ISSUE THREAD

**Issue by sagotsky** [CodeRect/bookmark-tab#1]
This is nitpicky on my part.  

I use an addon called vimperator.  One of its features is it highlights all the links on a page and assigns them numbers so I can click links by typing their numbers instead of using the mouse.  

bookmark-tab appears to use divs with click events on its node containers for folders.  vimperator is not identifying these as clickable so I don't get a number for them.  Swapping out the div for an anchor tag makes things happy.

In the addon currently release, all that meant was changing

```js
var jqNode = jQuery('<div></div>')
```
into
```js
var jqNode = jQuery('<a></a>')
```
in coderectTree.js's createNode.  I was planning on making a PR here, but it looks like the code has changed significantly so I'm just making an issue instead.

**Comment by CodeRect** [comment]
hey sagotsky,

thank you for your feedback - i downloaded vimperator and made sure that the next version will support the highlighting of links - see d5f24ba6de675d90d1e4ba554bbf432c96d5dcdd

thanks again - simon

**Comment by sagotsky** [comment]
TY, great addon!
